// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultSidebar: typeof import('./src/components/sidebars/DefaultSidebar.vue')['default']
    DispatchRoutePy: typeof import('./src/components/python/DispatchRoutePy.vue')['default']
    'IEva:arrowBackOutline': typeof import('~icons/eva/arrow-back-outline')['default']
    'IFa6Brands:github': typeof import('~icons/fa6-brands/github')['default']
    'IFaBrands:github': typeof import('~icons/fa-brands/github')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'INoto:crocodile': typeof import('~icons/noto/crocodile')['default']
    'IPh:caretDownBold': typeof import('~icons/ph/caret-down-bold')['default']
    'IPh:caretRightBold': typeof import('~icons/ph/caret-right-bold')['default']
    PythonSidebar: typeof import('./src/components/sidebars/PythonSidebar.vue')['default']
    RenderMd: typeof import('./src/components/markdown/RenderMd.vue')['default']
    RenderMdPy: typeof import('./src/components/python/RenderMdPy.vue')['default']
    RenderPyDocstring: typeof import('./src/components/python/RenderPyDocstring.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticPyCodeBlock: typeof import('./src/components/python/StaticPyCodeBlock.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
