# - Requirement:  local file ./goinfer.json
# - Build:        DOCKER_BUILDKIT=1 docker compose build
# - Run:          docker compose up
# - Stop:         CTRL + C
# - Clean:        docker compose down

services:
  goinfer-llama:
    image: goinfer-llama
    container_name: goinfer-llama
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - llama_git_tag=b6089
        - CUDA_VERSION=12.9
        - CUDA_PATCH=1
        - UBUNTU_VERSION=24.04
    command: -local
    ports: [5143:5143]
    configs: [goinfer.json]
    volumes:
      # goinfer.json must contain: "models_dir":"/models"
      # Define your custom models_dir in the ".env" file
      - ${models_dir:-./models}:/models
      - ${ccache_dir:-./.ccache}:/root/.ccache
      - ${go_cache_dir:-./.go}:/root/go
    environment:
      - TZ=UTC0 # time.Unix() uses UTC instead of local time zone
    # restart: unless-stopped

configs:
  goinfer.json:
    # file: ./goinfer.json
    content: '{"models_dir":"/models"}'

